name: CI — build

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps & ccache
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache wget

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Install CMake 4.0.0
        run: |
          # скачиваем оф. инсталлятор CMake 4.0.0 и ставим в /usr/local
          wget -q https://github.com/Kitware/CMake/releases/download/v4.0.0/cmake-4.0.0-linux-x86_64.sh -O /tmp/cmake-4.sh
          chmod +x /tmp/cmake-4.sh
          sudo /tmp/cmake-4.sh --skip-license --prefix=/usr/local
          cmake --version

      - name: Configure (CMake)
        run: |
          mkdir -p build
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror -Wpedantic"

      - name: Build
        run: cmake --build build --parallel

      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/
