name: Build & Release

on:
  push:
    tags:
      - 'v*' # запускается теге вида v1.0 и т.д.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget ccache

      - name: Install CMake 3.30.2
        run: |
          wget -q https://github.com/Kitware/CMake/releases/download/v3.30.2/cmake-3.30.2-linux-x86_64.sh -O /tmp/cmake.sh
          chmod +x /tmp/cmake.sh
          sudo /tmp/cmake.sh --skip-license --prefix=/usr/local
          cmake --version

      - name: Configure and build
        run: |
          rm -rf build
          mkdir -p build
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel

      - name: Package binary
        run: |
          mkdir -p release
          cp build/num_convert release/
          chmod +x release/num_convert
          cd release && tar -czf num_convert-linux.tar.gz num_convert

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: num_convert-linux
          path: release/num_convert-linux.tar.gz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/num_convert-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
